config/routes.rb
Rails.application.routes.draw do
  root "users#new"

  resources :users, only: %i[ new create ]

  resources :rooms do
    resources :messages, module: :rooms

    member do
      post :generate_hash
      delete :destroy_hash
      get :check
      post :join
      get :confirm
      delete :leave
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  include Slugable

  belongs_to :user
  has_many :messages, dependent: :destroy

  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users

  before_validation :set_max_users, on: :create

  MAX_USERS = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :max_users, presence: true, inclusion: { in: MAX_USERS }, numericality: { only_integer: true }
  validates :user_id, presence: true
  validates :logo, presence: true, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])

  scope :search, ->(query) { where("LOWER(name) LIKE ?", "%#{query}%") }

  def generate_hash_code
    self.hash_code = SecureRandom.hex(5)
    self.visibility = true
  end

  def destroy_hash_code
    self.hash_code = nil
    self.visibility = false
  end

  private

  def set_max_users
    self.max_users = 10
  end
end

app/controllers/rooms/messages_controller.rb
class Rooms::MessagesController < ApplicationController
  before_action :set_room
  before_action :authenticate_user!
  def create
    @message = @room.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.append("messages", @message) }
        format.html { redirect_to room_path(@room) }
      end
    end
  end

  private

  def set_room
    @room = Room.friendly.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content, assets: []).merge(user: current_user)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[show destroy edit update generate_hash destroy_hash check join confirm leave]

  def index
    if params[:query].present?
      query = params[:query].downcase
      @pagy, @rooms = pagy(Room.search(query))
    else
      @pagy, @rooms = pagy(Room.order(created_at: :desc), limit: 5)
    end

    authorize @rooms
  end

  def show
    authorize @room
    redirect_to confirm_room_path(@room) unless room_session_valid?
    set_message
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      create_room_user_session!
      redirect_to @room, notice: t("controller.rooms.create.success", room: @room.name)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @room
  end

  def update
    authorize @room
    if @room.update(room_params)
      redirect_to @room, notice: t("controller.rooms.update.success", room: @room.name)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @room
    @room.destroy
    redirect_to rooms_path, notice: t("controller.rooms.destroy.success", room: @room.name)
  end

  def check; end

  def leave
    @user_room = @room.room_users.find_by(user_id: current_user.id)
    @user_room&.destroy
    session[:checked_room_user] = nil
    redirect_to rooms_path, notice: t("controller.rooms.leave.success", room: @room.name)
  end

  def confirm
    if room_session_valid?
      redirect_to room_path(@room), notice: t("controller.rooms.confirm.success", room: @room.name)
    end
  end

  def join
    if @room.user.id == current_user.id || @room.hash_code == params[:hash_code]
      create_room_user_session!
      redirect_to room_path(@room), notice: t("controller.rooms.join.success", room: @room.name)
    else
      redirect_to check_room_path(@room), alert: t("controller.rooms.join.error")
    end
  end

  def generate_hash
    authorize @room
    @room.generate_hash_code
    @room.save
    redirect_to edit_room_path(@room), notice: t("controller.rooms.generate_hash.success")
  end

  def destroy_hash
    authorize @room
    @room.destroy_hash_code
    @room.save
    redirect_to edit_room_path(@room), notice: t("controller.rooms.destroy_hash.success")
  end

  private

  def room_session_valid?
    session[:checked_room_user] == @room.id && @room.users.include?(current_user)
  end

  def create_room_user_session!
    session[:checked_room_user] = @room.id
    @room.room_users.find_or_create_by(user_id: current_user.id)
  end

  def set_room
    @room = Room.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to rooms_path, alert: t("controller.rooms.errors.not_found")
  end

  def set_message
    @messages = @room.messages
    @message = Message.new
  end

  def room_params
    params.require(:room).permit(:name, :visibility, :user_id, :hash_code, :logo,
                                 :max_users, :password, :image_background)
  end
end

app/helpers/rooms/messages_helper.rb
module Rooms::MessagesHelper
  def render_attachments(message)
    return unless message.assets.attached?

    content_tag :div, class: "media" do
      message.assets.map do |asset|
        if asset.content_type.starts_with?("image")
          image_tag asset, class: "w-48 h-48 object-cover"
        elsif asset.content_type.starts_with?("audio")
          audio_tag asset, controls: true, class: "w-full"
        elsif asset.content_type.starts_with?("video")
          video_tag asset, controls: true, class: "w-full"
        else
          link_to "Download", rails_blob_path(asset, disposition: "attachment")
        end
      end.join.html_safe
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_background_url(room)
    room.image_background.present? ? room.image_background : "https://img.freepik.com/free-photo/cement-texture_1194-6523.jpg"
  end
end

app/views/rooms/shared/_form.html.haml
= form_with(model: room, class: "space-y-4") do |f|
  = f.label :hash_code, t("rooms.shared.form.generate_hash_code"),                |
    class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" |
  %figure.max-w-lg
    .relative.w-full.flex.items-center.max-w-sm.mx-auto
      .relative.w-full
        .absolute.inset-y-0.start-0.flex.items-center.ps-3.pointer-events-none.dark:text-white
          %i.fa-solid.fa-share
        %input#simple-search.bg-gray-50.border.border-gray-300.text-gray-900.text-sm.rounded-lg.focus:ring-blue-500.focus:border-blue-500.block.w-full.ps-10.dark:bg-gray-700.dark:border-gray-600.dark:placeholder-gray-400.dark:text-white.dark:focus:ring-blue-500.dark:focus:border-blue-500{:class => "p-2.5", :disabled => "disabled", :type => "text", :value => "#{room.hash_code if room.hash_code.present?}"}/
      - if room.hash_code
        = link_to destroy_hash_room_path(room), data: { turbo_method: :delete }, class: "p-2.5 ms-2 text-sm font-medium text-white bg-red-700 rounded-lg border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800" do
          %i.fa-solid.fa-x
      - else
        = link_to generate_hash_room_path(room), data: { turbo_method: :post },
        class: "p-2.5 ms-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do |
          %i.fa-solid.fa-arrows-rotate
  %hr.w-48.h-1.mx-auto.my-4.bg-gray-100.border-0.rounded.md:my-10.dark:bg-gray-700/
  = f.label :max_users, t("rooms.shared.form.max_users"),
    class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"
  = f.select :max_users,                                                                                                                                                                                                                                                         |
    options_for_select(Room::MAX_USERS, selected: room.max_users), { prompt: t("rooms.shared.form.max_users") },                                                                                                                                                                             |
    class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" |
  = form_model_errors(room, :max_users)
  %hr.w-48.h-1.mx-auto.my-4.bg-gray-100.border-0.rounded.md:my-10.dark:bg-gray-700/
  = f.label :image_background, t("rooms.shared.form.room_background"),                                  |
    class: "block mb-2 text-sm font-medium text-center text-gray-900 dark:text-white" |
  %figure.max-w-lg{"data-controller" => "preview-image"}
    %img.h-auto.max-w-full.rounded-lg{:alt => "Preview image", "data-preview-image-target" => "preview", :src => "#{room.image_background.present? ? room.image_background : 'https://placehold.co/500x200?text=Background'}", :style => "width: 500px; height: 200px; object-fit: cover;"}/
    %p.text-sm.text-red-500.mt-2{"data-preview-image-target" => "error"}
    %br/
    .relative.w-full.flex.items-center.max-w-sm.mx-auto
      .absolute.inset-y-0.start-0.flex.items-center.ps-3.pointer-events-none.text-white
        %i.fa-solid.fa-image
      = f.text_field :image_background,
        id: "simple-search", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500",
        placeholder: t("rooms.shared.form.room_background_placeholder"),
        data: { action: "input->preview-image#updatePreview", preview_image_target: "input" }
      - if room.image_background.present?
        %span.ms-2.text-sm.font-medium.text-white.bg-green-700.rounded-lg.border.border-green-700.focus:ring-4.focus:outline-none.focus:ring-green-300.dark:bg-green-600{:class => "p-2.5"}
          %i.fa-solid.fa-check
      = form_model_errors(room, :image_background)
  = f.submit t("rooms.shared.form.edit_submit"), class: "w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"

app/views/rooms/shared/_search.html.haml
= form_with url: path, method: :get, local: true, class: "relative" do |f|
  .absolute.inset-y-0.left-0.rtl:inset-r-0.rtl:right-0.flex.items-center.ps-3.pointer-events-none.text-white
    %i.fa-solid.fa-magnifying-glass
  = f.text_field :query, id: "table-search", placeholder: t("rooms.shared.form.search_placeholder"), class: "block p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"