config/routes.rb
Rails.application.routes.draw do
  root "users#new"

  resources :users, only: %i[ new create ]

  resources :rooms do
    resources :messages, module: :rooms

    member do
      post :generate_hash
      delete :destroy_hash
      get :check
      post :join
      get :confirm
      delete :leave
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  include Slugable

  belongs_to :user
  has_many :messages, dependent: :destroy

  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users

  before_validation :set_max_users, on: :create

  MAX_USERS = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :max_users, presence: true, inclusion: { in: MAX_USERS }, numericality: { only_integer: true }
  validates :user_id, presence: true
  validates :logo, presence: true, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])

  scope :search, ->(query) { where("LOWER(name) LIKE ?", "%#{query}%") }

  def generate_hash_code
    self.hash_code = SecureRandom.hex(5)
    self.visibility = true
  end

  def destroy_hash_code
    self.hash_code = nil
    self.visibility = false
  end

  private

  def set_max_users
    self.max_users = 10
  end
end

app/controllers/rooms/messages_controller.rb
class Rooms::MessagesController < ApplicationController
  before_action :set_room
  before_action :authenticate_user!
  def create
    @message = @room.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.append("messages", @message) }
        format.html { redirect_to room_path(@room) }
      end
    end
  end

  private

  def set_room
    @room = Room.friendly.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content, assets: []).merge(user: current_user)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[show destroy edit update generate_hash destroy_hash check join confirm leave]

  def index
    if params[:query].present?
      query = params[:query].downcase
      @pagy, @rooms = pagy(Room.search(query))
    else
      @pagy, @rooms = pagy(Room.order(created_at: :desc), limit: 5)
    end

    authorize @rooms
  end

  def show
    authorize @room
    redirect_to confirm_room_path(@room) unless room_session_valid?
    set_message
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      create_room_user_session!
      redirect_to @room, notice: t("controller.rooms.create.success", room: @room.name)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @room
  end

  def update
    authorize @room
    if @room.update(room_params)
      redirect_to @room, notice: t("controller.rooms.update.success", room: @room.name)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @room
    @room.destroy
    redirect_to rooms_path, notice: t("controller.rooms.destroy.success", room: @room.name)
  end

  def check; end

  def leave
    @user_room = @room.room_users.find_by(user_id: current_user.id)
    @user_room&.destroy
    session[:checked_room_user] = nil
    redirect_to rooms_path, notice: t("controller.rooms.leave.success", room: @room.name)
  end

  def confirm
    if room_session_valid?
      redirect_to room_path(@room), notice: t("controller.rooms.confirm.success", room: @room.name)
    end
  end

  def join
    if @room.user.id == current_user.id || @room.hash_code == params[:hash_code]
      create_room_user_session!
      redirect_to room_path(@room), notice: t("controller.rooms.join.success", room: @room.name)
    else
      redirect_to check_room_path(@room), alert: t("controller.rooms.join.error")
    end
  end

  def generate_hash
    authorize @room
    @room.generate_hash_code
    @room.save
    redirect_to edit_room_path(@room), notice: t("controller.rooms.generate_hash.success")
  end

  def destroy_hash
    authorize @room
    @room.destroy_hash_code
    @room.save
    redirect_to edit_room_path(@room), notice: t("controller.rooms.destroy_hash.success")
  end

  private

  def room_session_valid?
    session[:checked_room_user] == @room.id && @room.users.include?(current_user)
  end

  def create_room_user_session!
    session[:checked_room_user] = @room.id
    @room.room_users.find_or_create_by(user_id: current_user.id)
  end

  def set_room
    @room = Room.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to rooms_path, alert: t("controller.rooms.errors.not_found")
  end

  def set_message
    @messages = @room.messages
    @message = Message.new
  end

  def room_params
    params.require(:room).permit(:name, :visibility, :user_id, :hash_code, :logo,
                                 :max_users, :password, :image_background)
  end
end

app/helpers/rooms/messages_helper.rb
module Rooms::MessagesHelper
  def render_attachments(message)
    return unless message.assets.attached?

    content_tag :div, class: "media" do
      message.assets.map do |asset|
        if asset.content_type.starts_with?("image")
          image_tag asset, class: "w-48 h-48 object-cover"
        elsif asset.content_type.starts_with?("audio")
          audio_tag asset, controls: true, class: "w-full"
        elsif asset.content_type.starts_with?("video")
          video_tag asset, controls: true, class: "w-full"
        else
          link_to "Download", rails_blob_path(asset, disposition: "attachment")
        end
      end.join.html_safe
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_background_url(room)
    room.image_background.present? ? room.image_background : "https://img.freepik.com/free-photo/cement-texture_1194-6523.jpg"
  end
end

app/views/rooms/check.html.haml
.w-screen.h-screen.flex-col.flex.items-center.justify-center.bg-gray-100.dark:bg-gray-900
  %section.bg-gray-50.dark:bg-gray-900
    .flex.flex-col.items-center.justify-center.px-6.py-8.mx-auto.md:h-screen.lg:py-0
      .w-full.bg-white.rounded-lg.shadow.dark:border.md:mt-0.sm:max-w-md.xl:p-0.dark:bg-gray-800.dark:border-gray-700
        .p-6.space-y-4.md:space-y-6.sm:p-8
          %h1.text-xl.font-bold.leading-tight.tracking-tight.text-gray-900.md:text-2xl.dark:text-white
            = t("rooms.check.title")
          = form_with url: join_room_path(@room), html: { class: "max-w-sm mx-auto" } do |f|
            .mb-5
              = f.label :hash_code, "code", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              = f.text_field :hash_code, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "dwd43dcvw", required: true
              %br
              = f.submit t("rooms.check.code_verification"), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"

app/views/rooms/confirm.html.haml
.w-screen.h-screen.flex-col.flex.items-center.justify-center.bg-gray-100.dark:bg-gray-900
  %section.bg-gray-50.dark:bg-gray-900
    .flex.flex-col.items-center.justify-center.px-6.py-8.mx-auto.md:h-screen.lg:py-0
      .w-full.bg-white.rounded-lg.shadow.dark:border.md:mt-0.sm:max-w-md.xl:p-0.dark:bg-gray-800.dark:border-gray-700
        .p-6.space-y-4.md:space-y-6.sm:p-8
          %h1.text-xl.font-bold.leading-tight.tracking-tight.text-gray-900.md:text-2xl.dark:text-white
            = t("rooms.confirm.title", room: @room&.name)
          .relative.overflow-x-auto.shadow-md.sm:rounded-lg
            %table.w-full.text-sm.text-left.rtl:text-right.text-gray-500.dark:text-gray-400
              %tbody
                - @room&.users&.each do |user|
                  %tr.border-b.border-gray-200.dark:border-gray-700
                    %th.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.bg-gray-50.dark:text-white.dark:bg-gray-800{:scope => "row"}
                      = user&.name
                    %td.px-6.py-4.bg-gray-50.dark:bg-gray-800
                      .flex.items-center.justify-center.ml-auto.text-xs.text-white.bg-green-500.h-4.w-4.rounded.leading-none
          = form_with url: join_room_path(@room), html: { class: "max-w-sm mx-auto" } do |f|
            = f.submit t("rooms.confirm.join"), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"

app/views/rooms/edit.html.haml
.w-screen.h-screen.flex-col.flex.items-center.justify-center.bg-gray-100.dark:bg-gray-900
  %section.bg-gray-50.dark:bg-gray-900
    .flex.flex-col.items-center.justify-center.px-6.py-8.mx-auto.md:h-screen.lg:py-0
      .w-full.bg-white.rounded-lg.shadow.dark:border.md:mt-0.sm:max-w-md.xl:p-0.dark:bg-gray-800.dark:border-gray-700
        .p-6.space-y-4.md:space-y-6.sm:p-8.text-center
          %h1.text-xl.font-bold.leading-tight.tracking-tight.text-gray-900.md:text-2xl.dark:text-white
            = t("rooms.edit.title", room: @room&.name)
          = render "rooms/shared/form", room: @room
          %a.inline-flex.items-center.text-center.text-blue-600.dark:text-blue-500.hover:underline{:href => "#{room_path(@room)}"}
            = t("application.back")

app/views/rooms/index.html.haml
.w-screen.h-screen.flex-col.flex.items-center.justify-center.bg-gray-100.dark:bg-gray-900
  .relative.overflow-x-auto.shadow-md.sm:rounded-lg
    .flex.flex-column.sm:flex-row.flex-wrap.space-y-4.sm:space-y-0.items-center.justify-between.pb-4
      %div
        = link_to new_room_path, class: "text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" do
          %i.fa-solid.fa-plus
          = t("rooms.index.create_room")
      = render "rooms/shared/search", path: rooms_path
    %table.w-full.text-sm.text-left.rtl:text-right.text-gray-500.dark:text-gray-400
      %thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
        %tr
          %th.px-6.py-3{:scope => "col"}
            %i.fa-solid.fa-bars
          %th.px-6.py-3{:scope => "col"}
          %th.px-6.py-3{:scope => "col"}
            %i.fa-solid.fa-door-open
            = t("rooms.index.name")
          %th.px-6.py-3{:scope => "col"}
            %i.fa-solid.fa-user
            = t("rooms.index.author")
          %th.px-6.py-3{:scope => "col"}
            %i.fa-solid.fa-users
            = t("rooms.index.users")
          %th.px-6.py-3{:scope => "col"}
            %i.fa-solid.fa-clock
            = t("rooms.index.created_at")
          %th.px-6.py-3{:scope => "col"}
            %i.fa-solid.fa-eye
            = t("rooms.index.status")
          %th.px-6.py-3{:scope => "col"}
            %i.fa-solid.fa-bars
            = t("rooms.index.actions")
      %tbody
        - if @rooms.any?
          - @rooms.each do |room|
            %tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700.hover:bg-gray-50.dark:hover:bg-gray-600
              %td.px-6.py-4
                %i.fa-solid.fa-bars
              %td.w-4.p-4{:style => "padding: 19px;"}
                .flex.items-center{:style => "width: 39px;"}
                  = image_tag(room.logo, class: "w-10 h-10 p-1 rounded-full ring-2 ring-gray-300 dark:ring-gray-500") if room&.logo.present?
              %th.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white{:scope => "row"}
                = room.name
              %td.px-6.py-4
                = room.user&.name
              %td.px-6.py-4
                = room.users&.count
                \/
                %strong= room.max_users
              %td.px-6.py-4
                = time_ago_in_words(room.created_at)
              %td.px-6.py-4
                - if room.visibility == false
                  %i.fa-solid.fa-lock-open
                - else
                  %i.fa-solid.fa-lock
              %td.px-6.py-4
                = link_to confirm_room_path(room), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center me-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do
                  %i.fa-solid.fa-arrow-right
                - if room.user&.id == current_user&.id
                  = link_to room_path(room), data: { turbo_method:   :delete }, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center me-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-blue-800" do
                    %i.fa-solid.fa-trash
                  = link_to edit_room_path(room), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center me-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-blue-800" do
                    %i.fa-solid.fa-pen-to-square
        - else
          .p-4.mb-4.text-sm.text-yellow-800.rounded-lg.bg-yellow-50.dark:bg-gray-800.dark:text-yellow-300{role: "alert"}
            %span.font-medium= t("rooms.index.no_rooms")
  = render "shared/pagination", pagy: @pagy, collection: @rooms

app/views/rooms/new.html.haml
.w-screen.h-screen.flex-col.flex.items-center.justify-center.bg-gray-100.dark:bg-gray-900
  %section.bg-gray-50.dark:bg-gray-900
    .flex.flex-col.items-center.justify-center.px-6.py-8.mx-auto.md:h-screen.lg:py-0
      .w-full.bg-white.rounded-lg.shadow.dark:border.md:mt-0.sm:max-w-md.xl:p-0.dark:bg-gray-800.dark:border-gray-700
        .p-6.space-y-4.md:space-y-6.sm:p-8.text-center
          %h1.text-xl.font-bold.leading-tight.tracking-tight.text-gray-900.md:text-2xl.dark:text-white
            = t("rooms.new.title")
          = form_with(model: @room, class: "space-y-4", data: { controller: "gif-generator" }) do |f|
            %div
              .flex.items-center.space-x-4{:style => "place-self: center;"}
                %img#gif-image.rounded-full.w-40.h-40.object-cover{:alt => "image description", "data-gif-generator-target" => "image", :src => "#{@room.logo.present? ? @room.logo : 'https://placehold.co/160x160?text=Gif+Generator'}"}/
                %button#generate-gif.text-white.bg-gradient-to-br.from-purple-600.to-blue-500.hover:bg-gradient-to-bl.focus:ring-4.focus:outline-none.focus:ring-blue-300.dark:focus:ring-blue-800.font-medium.rounded-full.text-sm.px-5.text-center.me-2.mb-2{:class => "py-2.5", "data-action" => "gif-generator#generate", :style => "position: absolute;\n                    margin-left: 116px;\n                    margin-top: 110px;", :type => "button"}
                  %i.fa-solid.fa-arrows-rotate
              = form_model_errors(@room, :logo)
              %hr.w-48.h-1.mx-auto.my-4.bg-gray-100.border-0.rounded.md:my-10.dark:bg-gray-700/
              = f.hidden_field :logo, id: "gif-url", data: { gif_generator_target: "hiddenField" }
              = f.label :name, t("rooms.new.room_name"), class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              = f.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white", placeholder: t("rooms.new.title_room_placeholder")
              = form_model_errors(@room, :name)
            = f.submit t("rooms.shared.form.new_submit"), class: "w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
            %a.inline-flex.items-center.text-center.text-blue-600.dark:text-blue-500.hover:underline{:href => rooms_path}
              = t("application.back")

app/views/rooms/show.html.haml
.w-screen.h-screen.flex-col.flex.items-center.justify-center.bg-gray-100.dark:bg-gray-900
  .flex.h-screen.antialiased.text-gray-800
    .flex.flex-row.h-full.w-full.overflow-x-hidden
      = render "rooms/chat/sidebar"
      = render "rooms/chat/chat"