config/routes.rb
Rails.application.routes.draw do
  root "users#new"

  resources :users, only: %i[ new create ]

  resources :rooms do
    resources :messages, module: :rooms

    member do
      post :generate_hash
      delete :destroy_hash
      get :check
      post :join
      get :confirm
      delete :leave
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  include Slugable

  belongs_to :user
  has_many :messages, dependent: :destroy

  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users

  before_validation :set_max_users, on: :create

  MAX_USERS = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :max_users, presence: true, inclusion: { in: MAX_USERS }, numericality: { only_integer: true }
  validates :user_id, presence: true
  validates :logo, presence: true, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])

  scope :search, ->(query) { where("LOWER(name) LIKE ?", "%#{query}%") }

  def generate_hash_code
    self.hash_code = SecureRandom.hex(5)
    self.visibility = true
  end

  def destroy_hash_code
    self.hash_code = nil
    self.visibility = false
  end

  private

  def set_max_users
    self.max_users = 10
  end
end

app/controllers/rooms/messages_controller.rb
class Rooms::MessagesController < ApplicationController
  before_action :set_room
  before_action :authenticate_user!
  def create
    @message = @room.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.append("messages", @message) }
        format.html { redirect_to room_path(@room) }
      end
    end
  end

  private

  def set_room
    @room = Room.friendly.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content, assets: []).merge(user: current_user)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[show destroy edit update generate_hash destroy_hash check join confirm leave]

  def index
    if params[:query].present?
      query = params[:query].downcase
      @pagy, @rooms = pagy(Room.search(query))
    else
      @pagy, @rooms = pagy(Room.order(created_at: :desc), limit: 5)
    end

    authorize @rooms
  end

  def show
    authorize @room
    redirect_to confirm_room_path(@room) unless room_session_valid?
    set_message
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      create_room_user_session!
      redirect_to @room, notice: t("controller.rooms.create.success", room: @room.name)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @room
  end

  def update
    authorize @room
    if @room.update(room_params)
      redirect_to @room, notice: t("controller.rooms.update.success", room: @room.name)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @room
    @room.destroy
    redirect_to rooms_path, notice: t("controller.rooms.destroy.success", room: @room.name)
  end

  def check; end

  def leave
    @user_room = @room.room_users.find_by(user_id: current_user.id)
    @user_room&.destroy
    session[:checked_room_user] = nil
    redirect_to rooms_path, notice: t("controller.rooms.leave.success", room: @room.name)
  end

  def confirm
    if room_session_valid?
      redirect_to room_path(@room), notice: t("controller.rooms.confirm.success", room: @room.name)
    end
  end

  def join
    if @room.user.id == current_user.id || @room.hash_code == params[:hash_code]
      create_room_user_session!
      redirect_to room_path(@room), notice: t("controller.rooms.join.success", room: @room.name)
    else
      redirect_to check_room_path(@room), alert: t("controller.rooms.join.error")
    end
  end

  def generate_hash
    authorize @room
    @room.generate_hash_code
    @room.save
    redirect_to edit_room_path(@room), notice: t("controller.rooms.generate_hash.success")
  end

  def destroy_hash
    authorize @room
    @room.destroy_hash_code
    @room.save
    redirect_to edit_room_path(@room), notice: t("controller.rooms.destroy_hash.success")
  end

  private

  def room_session_valid?
    session[:checked_room_user] == @room.id && @room.users.include?(current_user)
  end

  def create_room_user_session!
    session[:checked_room_user] = @room.id
    @room.room_users.find_or_create_by(user_id: current_user.id)
  end

  def set_room
    @room = Room.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to rooms_path, alert: t("controller.rooms.errors.not_found")
  end

  def set_message
    @messages = @room.messages
    @message = Message.new
  end

  def room_params
    params.require(:room).permit(:name, :visibility, :user_id, :hash_code, :logo,
                                 :max_users, :password, :image_background)
  end
end

app/helpers/rooms/messages_helper.rb
module Rooms::MessagesHelper
  def render_attachments(message)
    return unless message.assets.attached?

    content_tag :div, class: "media" do
      message.assets.map do |asset|
        if asset.content_type.starts_with?("image")
          image_tag asset, class: "w-48 h-48 object-cover"
        elsif asset.content_type.starts_with?("audio")
          audio_tag asset, controls: true, class: "w-full"
        elsif asset.content_type.starts_with?("video")
          video_tag asset, controls: true, class: "w-full"
        else
          link_to "Download", rails_blob_path(asset, disposition: "attachment")
        end
      end.join.html_safe
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_background_url(room)
    room.image_background.present? ? room.image_background : "https://img.freepik.com/free-photo/cement-texture_1194-6523.jpg"
  end
end

app/views/rooms/chat/_chat.html.haml
:css
  .background-changer {
    background: url('#{room_background_url(@room)}');
    background-size: cover;
  }
.flex.flex-col.flex-auto.h-full.p-6{:class => "w-[1256px]"}
  .flex.flex-col.flex-auto.flex-shrink-0.rounded-2xl.bg-gray-100.h-full.p-4.background-changer
    .flex.flex-col.h-full.overflow-x-auto.mb-4
      .flex.flex-col.h-full
        .grid.gap-y-2{"data-controller" => "messages"}
          = turbo_stream_from @room
          #notifications
          = turbo_stream_from "messages"
          #messages
            - @messages&.each do |message|
              = render partial: "rooms/messages/message", locals: { message: message }
    = form_with(model: [@room, @message], local: false, remote: true,                                                |
      data: { controller: "messages file-preview", action: "submit->file-preview#hidePreviewAfterSubmit"}) do |form| |
      = render "rooms/messages/form", form: form

app/views/rooms/chat/_sidebar.html.haml
.flex.flex-col.flex-auto.h-full.p-6
  .flex.flex-col.flex-auto.flex-shrink-0.rounded-2xl.bg-gray-100.h-full.p-4
    .flex.flex-row.items-center.justify-center.h-12.w-full
      .flex.items-center.justify-center.rounded-2xl.text-indigo-700.bg-indigo-100.h-10.w-10
        %i.fa-regular.fa-comments
      .ml-2.font-bold.text-2xl= @room&.name
    .flex.flex-col.items-center.bg-indigo-100.border.border-gray-200.mt-4.w-full.py-6.px-4.rounded-lg
      .h-20.w-20.rounded-full.border.overflow-hidden
        = image_tag(current_user&.avatar, class: "h-full w-full") if current_user&.avatar&.attached?
      .text-sm.font-semibold.mt-2= current_user&.name
    .flex.flex-col.mt-8
      .flex.flex-row.items-center.justify-between.text-xs
        %span.font-bold= t("rooms.chat.sidebar.active_users")
        = turbo_stream_from "user_count"
        %span.flex.items-center.justify-center.bg-gray-300.h-4.w-4.rounded-full
          #user_count
            = render "rooms/chat/user_count", room: @room
      .flex.flex-col.space-y-1.mt-4.-mx-2.h-48.overflow-y-auto
        = turbo_stream_from "users"
        #users
          - @room&.users&.each do |user|
            = render "rooms/chat/user", user: user
      .flex.flex-row.items-center.justify-between.text-xs.mt-6
        %hr.w-48.h-1.mx-auto.my-4.bg-gray-100.border-0.rounded.md:my-10.dark:bg-gray-700/
      .flex.flex-col.space-y-1.mt-4.-mx-2
        = link_to edit_room_path(@room), class: "py-2.5 text-center px-5 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" do
          = @room&.hash_code
        - if @room&.user&.id == current_user&.id
          = link_to edit_room_path(@room), class: "py-2.5 text-center px-5 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" do
            %i.fa-solid.fa-gear
            = t("rooms.chat.sidebar.edit")
        = link_to leave_room_path(@room), data: { turbo_method: :delete }, |
           class: "py-2.5 text-center px-5 me-2 mb-2 text-sm" |
          "font-medium text-red-900 focus:outline-none bg-white rounded-lg border border-red-200 hover:bg-gray-100 "          |
          "hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-red-100 dark:focus:ring-red-700 dark:bg-red-800"            |
          "dark:text-red-400 dark:border-red-600 dark:hover:text-white dark:hover:bg-red-700" do                              |
          %i.fa-solid.fa-right-from-bracket
          = t("rooms.chat.sidebar.leave")

app/views/rooms/chat/_user.html.haml
= turbo_frame_tag(dom_id(user)) do
  %button.flex.flex-row.items-center.hover:bg-gray-100.rounded-xl.p-2
    .flex.items-center.justify-center.h-8.w-8.bg-gray-200.rounded-full
      = user&.initials
    .ml-2.text-sm.font-semibold{:style => "margin-right: 10px;"}= user&.name
    - if user&.id == @room&.user&.id
      %i.fa-solid.fa-crown
    - else
      %i.fa-solid.fa-user

app/views/rooms/chat/_user_count.html.haml
%span.flex.items-center.justify-center.bg-gray-300.h-4.w-4.rounded-full
  = room&.users&.count